### ISSUE TITLE
PR is not getting merged

### ISSUE THREAD

**Issue by ephremdeme** [VAR-solutions/Algorithms#1145]
Why is PR is not getting merged to the main branch?. The last change that is merged is around 3 months old. is the repo not active?

**Comment by i-vishi** [comment]
@ephremdeme We are merging PRs. The repo was inactive for 2-3 months as the maintainers were busy. As any of the maintainers is free they start checkiing the PRS and take necessary action. Dont't worry, if you give a PR that is worth being merged, it will be merged.
Also, we are working on refactoring the diirectory structure, so we are merging to the master branch

**Comment by ephremdeme** [comment]
Thank you @i-vishi .
