### ISSUE TITLE
Convert Number to words

### ISSUE THREAD

**Issue by tatticoder** [VAR-solutions/Algorithms#1187]
I would like to add a algorithm which converts number entered by user into words.
example:
Input `100` 
Output `One Hundred` 
This will be useful when implementing a feature like automatically making a dummy cheque for user with amount filled.

**Comment by i-vishi** [comment]
@tatticoder It looks to be a good algorithm. Go ahead and implement it. Make sure to create a new directory and follow the guidelines mentioned in  the README. Also, while giving the PR, do not forget to mention this issue in the comment

**Comment by coding-sourabh** [comment]
I would like to work on it..

**Comment by sakshi0461** [comment]
@tatticoder Can you please assign this issue to me?

**Comment by tatticoder** [comment]
@coding-sourabh , @sakshi0461 I Can not assign this issue to you. Only collaborators can do that.
I added this issue because I wanted to work on this algorithm myself. Sorry if that mislead you

**Comment by sharmanityam252** [comment]
[include.docx](https://github.com/VAR-solutions/Algorithms/files/5316553/include.docx)

**Comment by i-vishi** [comment]
@tatticoder I have merged your PR. I am closing this issue. :heavy_check_mark:
