### ISSUE TITLE
Adding Hangman Game using python in Game theory

### ISSUE THREAD

**Issue by aniketsingh98571** [VAR-solutions/Algorithms#1333]
@i-vishi @ravivarshney01 Please assign me this issue as a part of Hactoberfest2020,

**Comment by aniketsingh98571** [comment]
I would like to work  on it @ravivarshney01 @i-vishi

**Comment by i-vishi** [comment]
@aniketsingh98571 I am assigning it to you. :+1:

**Comment by i-vishi** [comment]
No Progress
