### ISSUE TITLE
Adding TicTac-Toe using Java in Game theory.

### ISSUE THREAD

**Issue by aniketsingh98571** [VAR-solutions/Algorithms#1334]
@ravivarshney01 @i-vishi I would like to add tic-tac-toe game using Java in [Game theory](https://github.com/VAR-solutions/Algorithms/tree/dev/Combinatorial%20Game%20Theory/Tic-Tac-Toe%20Optimal%20Move)

**Comment by aniketsingh98571** [comment]
Please assign me this issue.

**Comment by i-vishi** [comment]
@aniketsingh98571 I am assigning this to you. It would be great, if you can make changes to the directory structute of [Tic-tac-toe](https://github.com/VAR-solutions/Algorithms/tree/dev/Combinatorial%20Game%20Theory/Tic-Tac-Toe%20Optimal%20Move) like 
`algorithm-name/language/code.extension`
You can put the current `cpp` code inside a new CPP folder and your `java` code inside Java folder.
