### ISSUE TITLE
Add Vertical order Tree Traversal algorithms in c++

### ISSUE THREAD

**Issue by GunjanMA** [VAR-solutions/Algorithms#1340]
I would like to add vertical order tree traversal in c++. Kindly assign this issue to me

**Comment by i-vishi** [comment]
@GunjanMA I am assigning this issue to you. Make sure to follow the instruction given in **CONTRIBUTING.MD**

**Comment by bohemian98** [comment]
Kindly assign this issue to me in JavaScript. I would like to implement this as part of Hacktober fest 2020.

**Comment by GunjanMA** [comment]
> @GunjanMA I am assigning this issue to you. Make sure to follow the instruction given in **CONTRIBUTING.MD**

@i-vishi Kindly merge PR #1368

**Comment by i-vishi** [comment]
Check the [comment](https://github.com/VAR-solutions/Algorithms/pull/1368#pullrequestreview-501528064) on #1368

**Comment by Manas502** [comment]
Can I work on this issue, if it's pending?
