### ISSUE TITLE
add README to Searching Directory

### ISSUE THREAD

**Issue by i-vishi** [VAR-solutions/Algorithms#1341]
Add a README.md file inside the [Searching Directory](https://github.com/VAR-solutions/Algorithms/tree/dev/Searching). The file should contain a table that has

- Columns of searching algorithms and programming languages(C, CPP, Python, Java, etc.)
- Add a row of each searching algorithm and mark a :heavy_check_mark: with a **LINK** to code if it is currently implemented in the corresponding programming language, else leave the cell blank.
- Do it for each searching algorithm.
- You can also change file names as per the algorithm to simplify the task. But do not forget to follow the nomenclature as:
`algorithm-name/ProgrammingLanguage/algorithm_code.extension`

Refer to [Sorting README](https://github.com/VAR-solutions/Algorithms/blob/dev/Sorting/README.md) and implement in the same manner.Refer to [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) or [Makrdown Guide](https://www.markdownguide.org/basic-syntax/) to get help with writing **Markdown**.

Example Scrrenshot is given below:
![ex-sortingREADME](https://user-images.githubusercontent.com/31544686/94911636-0fcb1280-04c4-11eb-91ea-78d4ca4e6cb7.png)

**Comment by vifeng** [comment]
Hi, can I take this issue please ?

**Comment by i-vishi** [comment]
@vifeng you can work on this issue. Give a PR referencing this issue and we will merge it if it meets our requirements.

**Comment by vifeng** [comment]
thanks. it's my second contributions... how do I reference the issue ? 
should I send my PR with a commit message as such : 
`
feat: add README to Searching Directory 

Each mark has a ✔️ with a LINK to the implemented code in the corresponding programming language.

Resolves: #1341`

**Comment by UshasriMavuri1999** [comment]
Hey @i-vishi , Can you please assign this issue to me?
I would like to work on this...

**Comment by 7s9n** [comment]
done : )
