### ISSUE TITLE
Longest Increasing Subsequence in O(N log N)

### ISSUE THREAD

**Issue by bohemian98** [VAR-solutions/Algorithms#1392]
I would like to implement the Longest Increasing Subsequence problem using Binary Search and Dynamic Programming in **worst-case complexity of N log N** as a part of Hacktober Fest 2020.

**Comment by i-vishi** [comment]
@bohemian98 [Longest Increasing subsequence](https://github.com/VAR-solutions/Algorithms/tree/dev/Dynamic%20Programming/Longest%20Increasing%20Subsequence) is already implemeted in CPP, Go, Java. It you want to contribute in another language, you can. If you find any problem in the current code, you can also improve it. 

I am closing this issue. If you wish to contribute, refer your PR to #1 or #163 or #1122
