### ISSUE TITLE
folders for separate languages

### ISSUE THREAD

**Issue by Phantsure** [VAR-solutions/Algorithms#59]
making separate folders for separate languages will help in maintaining a lot

**Comment by Phantsure** [comment]
@i-vishi should i do that but it would show that i removed all files and recreated them, so better that you make a CONTRIBUTING.md

**Comment by i-vishi** [comment]
@Phantsure Not Required. It is fine, one should only be concerned about algorithms, not the language

**Comment by Phantsure** [comment]
fine
